services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=/app/data/stars.db
